name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Test
      uses: docker://jerson/go:1.14
      with:
        args: sh -c "make test"
      
    - name: Binding
      uses: docker://jerson/go:1.14
      with:
        args: sh -c "make binding"
      
    - name: WASM
      uses: docker://jerson/go:1.14
      with:
        args: sh -c "make wasm"
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: output
      
