name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: test
      uses: docker://jerson/go:1.13
      with:
        args: sh -c "make test"
      
    - name: binding
      uses: docker://jerson/go:1.13
      with:
        args: sh -c make binding"
      
