name: Build Protobuf

on:
  push:
    paths:
      - '**.proto'

jobs:
  dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Build
        run: |
          make proto_dart_deps
          make proto_dart
      - name: Compress
        run: tar -czvf output.tar.gz -C output/dart .
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: proto_dart_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build
        run: |
          make proto_go_deps
          make proto_go
      - name: Compress
        run: tar -czvf output.tar.gz -C bridge/model .
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: proto_go_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ github.ref }}
          overwrite: true